workflows:
  ios-debug:
    name: IPA Build in Debug Mode
    environment:
      flutter: 3.24.5
      xcode: 16.3
      cocoapods: default
      # Variáveis de ambiente (opcional, se já definidas na interface)
      vars:
        APP_NAME: "CNN"
      ios_signing:
        provisioning_profiles:
          - com.cnn-brasil
        certificates:
          - dev-cert-cnn

    scripts:
      - name: Get flutter packages
        script: flutter packages pub get
      - name: Flutter build ipa
        script: flutter build ipa --flavor development

    artifacts:
      - build/ios/ipa/*.ipa
      - debug_symbols/**/*.dSYM
