workflows:
  flutter-prod:
    name: Flutter Production Build
    environment:
      flutter: 2.24.5
    scripts:
      - name: Build IPA
        script: |
          flutter build ipa \
            --release \
            --flavor production \
            --dart-define=envFlavor=production \
            --export-options-plist=ios/export_options.plist \
            --split-debug-info=debug_symbols \
            --obfuscate
    artifacts:
      - build/ios/ipa/*.ipa
      - debug_symbols/**/*.dSYM  # Inclui os dSYMs gerados
