// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5EMWWA-ufd9NDW_Lbto6Tqers_btbmKw',
    appId: '1:259226150264:android:5165917a625340b56f948d',
    messagingSenderId: '259226150264',
    projectId: 'cnn-ios',
    storageBucket: 'cnn-ios.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDXq693jSwnT5LCM1O0quHkK3LnpvHNTk',
    appId: '1:259226150264:ios:4befe0682b7183f56f948d',
    messagingSenderId: '259226150264',
    projectId: 'cnn-ios',
    storageBucket: 'cnn-ios.appspot.com',
    androidClientId:
        '259226150264-v07a3c5h2fb622iqqf2n5mrvvr17e40n.apps.googleusercontent.com',
    iosClientId:
        '259226150264-6io68qvfkq3o1i1olcp6euoanvkqjult.apps.googleusercontent.com',
    iosBundleId: 'com.agilecontent.cnn-brasil-dev',
  );
}
